// <auto-generated />
namespace ScrapSettlement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addKey));
        
        string IMigrationMetadata.Id
        {
            get { return "202010090243428_addKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
