//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrapSettlement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeighingSettlement
    {
        public int Id { get; set; }
        public string vocherNO { get; set; }
        public string CustmerCode { get; set; }
        public string personCode { get; set; }
        public string scrapCode { get; set; }
        public double netWeight { get; set; }
        public double proportion { get; set; }
        public double webUnitPrice { get; set; }
        public double settleUnitPrice { get; set; }
        public double settleAmount { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
